export const LISTING_PARAMS = [
  "postalCode",
  "subjectArea",
  "specialization",
  "degree",
  "marketContext",
  "distance",
  "hsGraduation",
  "nursingLicense",
  "education",
  "address",
  "city",
  "state",
  "firstName",
  "lastName",
  "emailAddress",
  "phoneNumber",
  "startDate",
  "universalLeadId",
  "pingEnabled",
  "setting",
  "resultSize",
  "utm_medium",
  "utm_source",
] as const;

export type ListingParam = (typeof LISTING_PARAMS)[number];
