import { Listing, Program, RawRFIResponse, RFIResponse } from "./types";

export const mockSchool = { id: 28, displayName: "Post University" };

export const mockPrograms: Program[] = [
  {
    programId: "1",
    displayName: "Management - Associate's",
    name: "Management",
    degreeName: "Associate's",
    programInfo: "",
    instructionMethod: "Online",
    school: mockSchool,
  },
  {
    programId: "2",
    displayName: "Business Administration - Bachelor's",
    name: "Business Administration",
    degreeName: "Bachelor's",
    programInfo: "",
    instructionMethod: "Online",
    school: mockSchool,
  },
  {
    programId: "3",
    displayName: "Accounting - Master's",
    name: "Accounting",
    degreeName: "Master's",
    programInfo: "",
    instructionMethod: "Online",
    school: mockSchool,
  },
];

export const mockRawRFIResponse: RawRFIResponse = {
  disclaimer: "<p>Disclaimer text...</p>",
  displayName: "AS - Management - Associate's",
  schoolName: "Post University",
  schoolId: 28,
  logo: { src: "https://example.com/logo.jpg", width: 350, height: 149 },
  useLeadId: true,
  useTrustedForm: true,
  tcpaDisclaimer: "By pressing Request Info...",
  tcpaCheckboxRequired: true,
  privacyPolicy: "<p>Privacy policy...</p>",
  questions: {
    schema: {
      properties: {
        firstName: {
          title: "First name",
          type: "string",
          required: true,
          maxLength: 30,
          pattern: "[a-zA-Z]{2,}",
        },
        lastName: {
          title: "Last name",
          type: "string",
          required: true,
          maxLength: 30,
          pattern: "[a-zA-Z]{2,}",
        },
        emailAddress: {
          title: "Email Address",
          type: "string",
          required: true,
          maxLength: 255,
        },
        primaryPhone: {
          title: "Phone Number",
          type: "string",
          required: true,
          maxLength: 15,
          pattern: "[0-9]{10}",
        },
        address: {
          title: "Address",
          type: "string",
          required: false,
          maxLength: 255,
        },
        city: {
          title: "City",
          type: "string",
          required: false,
          maxLength: 255,
        },
        postalCode: {
          title: "Postal Code",
          type: "string",
          required: false,
          maxLength: 10,
          pattern: "[0-9]{5}",
        },
        state: {
          title: "State/Province",
          type: "string",
          required: true,
          maxLength: 255,
          enum: ["AK", "AL"],
        },
        military: {
          title: "U.S. military affiliation",
          type: "string",
          required: true,
          maxLength: 255,
          enum: ["", "None", "Active Duty", "Dept of Defense", "Reserve", "Veteran", "Spouse", "Prefer not to disclose"],
        },
        startDate: {
          title: "Expected start date",
          type: "string",
          required: true,
          maxLength: 255,
          enum: ["", "Within 1 month", "1-3 months", "4-6 months", "7 months or more"],
        },
        "custom[101]": {
          title: "Do you currently have a computer at home with internet access?",
          type: "string",
          required: true,
          maxLength: 255,
          enum: ["Yes", "No"],
        },
      },
    },
    options: {
      fields: {
        firstName: { type: "text" },
        lastName: { type: "text" },
        emailAddress: { type: "email" },
        primaryPhone: { type: "tel" },
        address: { type: "text" },
        city: { type: "text" },
        postalCode: { type: "text" },
        state: { type: "select", optionLabels: ["Alaska", "Alabama"] },
        military: { type: "select", optionLabels: ["- Select One -", "None", "Active Duty", "Dept of Defense", "Reserve", "Veteran", "Spouse", "Prefer not to disclose"] },
        startDate: { type: "select", optionLabels: ["- Select One -", "Within 1 month", "1-3 months", "4-6 months", "7 months or more"] },
        "custom[101]": { type: "radio", optionLabels: ["Yes", "No"] },
      },
    },
  },
};

export const mockRFIResponse: RFIResponse = {
  disclaimer: "<p>Disclaimer text...</p>",
  displayName: "AS - Management - Associate's",
  schoolName: "Post University",
  schoolId: 28,
  logo: { src: "https://example.com/logo.jpg", width: 350, height: 149 },
  useLeadId: true,
  useTrustedForm: true,
  tcpaDisclaimer: "By pressing Request Info...",
  tcpaCheckboxRequired: true,
  questions: [
    {
      key: "firstName",
      title: "First name",
      type: "text",
      required: true,
      maxLength: 30,
      pattern: "[a-zA-Z]{2,}",
      options: null,
    },
    {
      key: "lastName",
      title: "Last name",
      type: "text",
      required: true,
      maxLength: 30,
      pattern: "[a-zA-Z]{2,}",
      options: null,
    },
    {
      key: "emailAddress",
      title: "Email Address",
      type: "email",
      required: true,
      maxLength: 255,
      pattern: null,
      options: null,
    },
    {
      key: "primaryPhone",
      title: "Phone Number",
      type: "tel",
      required: true,
      maxLength: 15,
      pattern: "[0-9]{10}",
      options: null,
    },
    {
      key: "address",
      title: "Address",
      type: "text",
      required: false,
      maxLength: 255,
      pattern: null,
      options: null,
    },
    {
      key: "city",
      title: "City",
      type: "text",
      required: false,
      maxLength: 255,
      pattern: null,
      options: null,
    },
    {
      key: "postalCode",
      title: "Postal Code",
      type: "text",
      required: false,
      maxLength: 10,
      pattern: "[0-9]{5}",
      options: null,
    },
    {
      key: "state",
      title: "State/Province",
      type: "select",
      required: true,
      maxLength: 255,
      pattern: null,
      options: [
        { value: "AK", displayName: "Alaska" },
        { value: "AL", displayName: "Alabama" },
      ],
    },
    {
      key: "military",
      title: "U.S. military affiliation",
      type: "select",
      required: true,
      maxLength: 255,
      pattern: null,
      options: [
        { value: "", displayName: "- Select One -" },
        { value: "None", displayName: "None" },
        { value: "Active Duty", displayName: "Active Duty" },
        { value: "Dept of Defense", displayName: "Dept of Defense" },
        { value: "Reserve", displayName: "Reserve" },
        { value: "Veteran", displayName: "Veteran" },
        { value: "Spouse", displayName: "Spouse" },
        { value: "Prefer not to disclose", displayName: "Prefer not to disclose" },
      ],
    },
    {
      key: "startDate",
      title: "Expected start date",
      type: "select",
      required: true,
      maxLength: 255,
      pattern: null,
      options: [
        { value: "", displayName: "- Select One -" },
        { value: "Within 1 month", displayName: "Within 1 month" },
        { value: "1-3 months", displayName: "1-3 months" },
        { value: "4-6 months", displayName: "4-6 months" },
        { value: "7 months or more", displayName: "7 months or more" },
      ],
    },
    {
      key: "custom[101]",
      title: "Do you currently have a computer at home with internet access?",
      type: "radio",
      required: true,
      maxLength: 255,
      pattern: null,
      options: [
        { value: "Yes", displayName: "Yes" },
        { value: "No", displayName: "No" },
      ],
    },
  ],
};

export const mockListings: Listing[] = [
  {
    name: "Management",
    message: "",
    schools: [
      {
        id: 28,
        displayName: "Post University",
        logo: { src: "https://example.com/logo.jpg", width: 350, height: 149 },
        locations: [
          {
            instructionMethod: "Online",
            programs: [
              {
                programId: "1",
                displayName: "Management - Associate's",
                degreeName: "Associate's",
                programInfo: "<p>Learn the fundamentals of business management.</p>",
              },
              {
                programId: "2",
                displayName: "Management - Bachelor's",
                degreeName: "Bachelor's",
                programInfo: "<p>Advanced management principles for working professionals.</p>",
                clickTrackingUrl: "https://example.com/click/2",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Business Administration",
    message: "",
    schools: [
      {
        id: 29,
        displayName: "Southern New Hampshire University",
        logo: { src: "https://example.com/snhu-logo.jpg", width: 350, height: 149 },
        locations: [
          {
            instructionMethod: "Online",
            programs: [
              {
                programId: "3",
                displayName: "Business Administration - Bachelor's",
                degreeName: "Bachelor's",
                programInfo: "<p>Prepare for leadership roles in business.</p>",
              },
              {
                programId: "4",
                displayName: "Business Administration - Master's",
                degreeName: "Master's",
                programInfo: "<p>MBA program designed for career advancement.</p>",
                clickTrackingUrl: "https://example.com/click/4",
              },
            ],
          },
        ],
      },
    ],
  },
];
